version: '3'
services:
  app:
    build:
      context: .
    command: gunicorn --workers 3 --bind 0.0.0.0:5000 -m 007 wsgi:app
    ports:
      - 8888:5000
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./keys:/app/keys
